### ISSUE TITLE
Add new dot density map for Employment by Sector, mapped to tract

### ISSUE THREAD

**Issue by daragoldberg** [NYCPlanning/labs-regional-viz#125]
Add a new dot density map "Employment by Sector" (dropdown) "Employment by Sector" (title); source data from Census Tract shapefile. 

Dots should stay locked, popup will pull data values associated with other geometries.

Value: 100 jobs

- EmOff15 #179FA5   "Office-based jobs"
- EmIns15 #e8c758   "Education & Healthcare jobs"
- EmInd15 #9e5dba   "Industrial jobs"
- EmSer15 #3db709   "Retail, Leisure & Hospitality jobs"
- EmOth15 #818387  "Other Services jobs"

**Comment by allthesignals** [comment]
Data available in Carto as region_employment_dotdensity_v0

**Comment by allthesignals** [comment]
This should go under "Jobs" right?

**Comment by allthesignals** [comment]
@andycochran hmmm might need some help configuring this

**Comment by daragoldberg** [comment]
Yes - should go under Jobs

**Comment by daragoldberg** [comment]
Data for popups:

**Municipality:**
EmOff15  
EmIns15
EmInd15
EmSer15
EmOth15

_Legend Title: Employment by Macro Sector, 2015_

**County, Subregion, Region:**
EmOff16
EmIns16
EmInd16
EmSer16
EmOth16

_Legend Title: Employment by Macro Sector, 2016_
