### ISSUE TITLE
Fix visualization of Prime Labor Force Change (dot density) at municipality

### ISSUE THREAD

**Issue by daragoldberg** [NYCPlanning/labs-regional-viz#134]
Similar issue to #131

Areas in Long Island have data that indicate losses, negative numbers, should be visualized as ORANGE dots, but visualization shows GAINS

examples: Syosset CDP, Bethpage CDP, Merrick CDP in Nassau County LI. 

Seems to be exclusive to LI

**Comment by allthesignals** [comment]
Hmmm is something supposed to be excluded from the shapefile? https://drive.google.com/drive/folders/1x-bkmY2r5mnwDpvwaJenhfANLJmZIN-i

**Comment by allthesignals** [comment]
Which columns does this dot density refer to?

**Comment by allthesignals** [comment]
lfpw0016si and lfpw0016? What's the difference?

**Comment by daragoldberg** [comment]
"si" is "sig" but variable names can only have 10 characters. It's the significance test. 

lfpw0016 is the value that should be mapped

**Comment by allthesignals** [comment]
@daragoldberg  i'm using `region_municipality_v0` as-is for this. Is that right?

**Comment by allthesignals** [comment]
![Screen Shot 2018-03-29 at 4.31.48 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5830e3bc40b5a00e00a5b4c0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206456fa6b7191a37cf1112a4f5b575ecc3c4a4356bcbbd671f3e57862804e0ebcd93e5b27c23f15afb9861eb901ba228c49d0e3ed8e1fd2f42f67b6d5db1063474f4dcbed5727a19041c95df449e24850a1103f60e2752431.png)
![Screen Shot 2018-03-29 at 4.31.07 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5830e3bc40b5a00e00a5b4c0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206456fa6b7191a37cf1112a4f5f585ecc3c4a4356bcbbd671f3e57862804e0ebcd93e5b27c23f15afb9861eb901ba228c49d0e3ed8e1fd2f42f67b6d5db1063474f4dcbed5727a19041c95df449e24850a1173363e4742431.png)
![Screen Shot 2018-03-29 at 4.29.03 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5830e3bc40b5a00e00a5b4c0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206456fa6b7191a37cf110224f5f5c5ecc3c4a4356bcbbd671f3e57862804e0ebcd93e5b27c23f15afb9861eb901ba228c49d0e3ed8e1fd2f42f67b6d5db1063474f4dcbed5727a19141c95df449e24850a1173f61e2712431.png)

@daragoldberg here's what I'm showing for the 3 towns. Lemme know what you think.
