### ISSUE TITLE
For multivariable (2+) maps, gray only the column with insignificant values, not the entire row

### ISSUE THREAD

**Issue by daragoldberg** [NYCPlanning/labs-regional-viz#135]
For **Housing units by Tenure, owner vs. renter**, only the column with insignificant value should be grayed.

Popup currently grays (invalidates) all data. In many cases, owner-occupied value IS significant and renter-occupied value IS NOT significant. Owner-occupied text should be in BLACK and renter-occupied value would be in GRAY.

**Comment by andycochran** [comment]
@daragoldberg It should be working this way. Could you give me an example of a specific geometry whose popup should show only renter OR owner as gray?

**Comment by andycochran** [comment]
Garden City Village shows correctly grayed Renter-occupied, incorrectly grayed owner-occupied. 

![image](https://user-images.githubusercontent.com/409279/37418876-97eff880-2789-11e8-9046-c4aa9de4f037.png)

**Comment by andycochran** [comment]
Same for Marbletown: 

![image](https://user-images.githubusercontent.com/409279/37419510-06917bd2-278b-11e8-97ae-618014f774ba.png)
