### ISSUE TITLE
Dots should not be clickable

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-regional-viz#157]
If a dot overlaps the edge of a geometry, and you click the dot instead of the polygon you see only popup info for the region. 

![image](https://user-images.githubusercontent.com/409279/37531727-59d36808-2913-11e8-93f9-57160b7f2ad8.png)

**Comment by daragoldberg** [comment]
@andycochran Dots should not be clickable, only the geographies should be clickable.  There will be a note in the About page with caveats about dot densities & geographic precision.

**Comment by andycochran** [comment]
@chriswhong Currently, something being clickable is based on the existence of `popupColumns` in the config. You can't have some layers clickable and others not. Ideas?

**Comment by andycochran** [comment]
This is maybe an edge case.
