### ISSUE TITLE
Change balance Pop up numbers for 2000 and 2016 to hundredths

### ISSUE THREAD

**Issue by daragoldberg** [NYCPlanning/labs-regional-viz#162]
Values for Balance 2000 and Balance 2016 (housing/jobs) should be to the hundredths

**Comment by andycochran** [comment]
We could add a `precision` variable to the map config. :thinking_face: But using a var in the middle of the conditional value formats might make the logic too complicated. Let's add a `format` variable to `popupColumns` that's optional and override the format logic that's currently in place.

**Comment by chriswhong** [comment]
Hotfixed in 103e36717a0c2199719133edeeb0d636d6ca3991
