### ISSUE TITLE
Can't hover geogs

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-regional-viz#177]
On some dot density maps, you cannot hover the geog polygons. 

To reproduce: 

- Go to the [prime-labor-force-gain](https://regional-viz.planninglabs.nyc/people/prime-labor-force-gain#7.1/40.857/-73.528) map
- Click next to go to renter-owner

I suspect the polygon layer is behind the dot layer when a new dot layer is added, but the polygon layer remains.

**Comment by daragoldberg** [comment]
@andycochran hover function not working following update #201/#192 to randomize color assignments on intro map.

**Comment by andycochran** [comment]
I don't think this is still an issue.
