### ISSUE TITLE
People - Map View

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-regional-viz#2]

**Comment by daragoldberg** [comment]
**People variable**, [Map Title] Subcategory by Corresponding Geography, and associated year or change period _(type of visualization)_

-**PopAden16** Population Density by Municipality, 2012-2016 5YR Average _(Chloropleth)_
-**PopP1016** Percent Population Change by County, 2010 to 2016 _(Chloropleth)_
-  can we label with net change and visualize percentage change?

-**PopA1016** Population Net Change by Municipality, 2006-2010 5YR Average to 2012-2016 5YR Average _(Dot Density)_
-**LFpw0016** Net Change in Prime Workforce (Labor Force Participants Age 25-54) by Municipality, 2000 to 2012-2016 _(Dot Density)_

**Comment by chriswhong** [comment]
Covered by #33
