### ISSUE TITLE
Houp1016 - Housing Permits by County 2010-2016 colors & breaks

### ISSUE THREAD

**Issue by daragoldberg** [NYCPlanning/labs-regional-viz#24]
**Total Units Permits 2010 to 2016**
<3,000   [ffffe0]
3,001 - 7,500 [ffffbe] 
7,501 - 15,000 [ffd37f]
15,001 - 30,000 [ffaa00]
> 30,000 [ff5500]

**Comment by allthesignals** [comment]
Closed by https://github.com/NYCPlanning/labs-regional-viz/pull/28
