### ISSUE TITLE
Jobs Map Views

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-regional-viz#3]

**Comment by daragoldberg** [comment]
Jobs variable, [Map Title] Subcategory by Corresponding Geography, and associated year or change period (type of visualization)

-**EmTot15** Total Employment by Municipality 2015, chloropleth
-**EmOff15**,  **EmIns15**, **EmInd15**, **EmSer15**, **EmOth15** Total Private Employment by Industry Sector [Office, Institutional, Industrial, Local Services, Other Services] 2015 , (Integrated dot density or individual variables that can be toggled) 

-**EmPr0016** Change in Annual Average Private Employment by County [by Super Sector], 2000 to 2016
- **EmOff0016** Change in Annual Average Office-Based Employment by County, 2000-2016
- **EmIns0016** Change in Annual Average Institutional Employment by County, 2000-2016
- **EmInd0016** Change in Annual Average Industrial Employment by County, 2000-2016
- **EmSer0016** Change in Annual Average Retail, Leisure & Hospitality Employment by County, 2000-2016
- **EmOth0016** Change in Annual Average Other Services Employment by County, 2000-2016

**Comment by chriswhong** [comment]
Covered by #33
