### ISSUE TITLE
Supporting Layers

### ISSUE THREAD

**Issue by daragoldberg** [NYCPlanning/labs-regional-viz#31]
Add two supporting layers:

- Regional Rail lines and stations, simple symbology (no need to distinguish between carriers, etc)
- Aerials - research options for a region-covering aerial tileset...

Add simple checkbox UI for these.

**Comment by andycochran** [comment]
@chriswhong I've added the UI in the branch `31-supporting-layers`. Reassigning to you to get the layers in.
