### ISSUE TITLE
Create template-based popup to be shown on click

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-regional-viz#37]
- Design work, figure where it will go
- Data work, figure what is in it (config-driven)
- Add query param so that the selected state is share-able

**Comment by andycochran** [comment]
New branch `37-popups`. 
Need to get popups pulling content from a component.

**Comment by andycochran** [comment]
Related to #11 (showing significance).

**Comment by allthesignals** [comment]
We talked about 2 approach: 

1. Use the MapboxGL API's `setHTML` method with the help of template literals. 
2. Create a popup component and use the `handleMouseClick` action to pass information down to that component, including positioning information, which would be used for querying or whatever.
