### ISSUE TITLE
Add Sequential Narrative Naviagation

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-regional-viz#39]
In sidebar, allow user to click previous and next to move between stories.

**Comment by allthesignals** [comment]
Add a YAML file in the `cms/` directory called `meta.yaml` (or whatever you want to name it). This will be rolled up into the JSON file as a top-level property. 

Then, go to `app/routes/application.js` and have the `forEach` skip this special meta file. You can do this either by [filtering](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter) it out of the value of `Array.keys or something else in the forEach.

You can use those properties directly, likely in application where the nivation lives.

**Comment by andycochran** [comment]
New branch `feature/39-sequential-narrative-navigation`: 
- [x] add `meta.yaml`, filter it from routes
- [x] app respects explicit positioning config, moved restructuring function into util, site header filters non-narrative maps, added tests
- [x] style prev/next buttons
- [ ] add computed properties to `map.js` controller to get the prev/next links from `meta.yaml`
- [ ] add `link-to` to prev/next buttons, using `disabled` class for first/last pages.

**Comment by andycochran** [comment]
I need to hand this off to someone (@allthesignals?) to rig up the prev/next links.

**Comment by andycochran** [comment]
@allthesignals I think [this line](https://github.com/NYCPlanning/labs-regional-viz/blob/feature/39-sequential-narrative-navigation/app/controllers/map.js#L22)… 

```js
return maps[currentPosition - 1];
```

…is finding the map in the unfiltered array of maps. So getting it by index gets the wrong map, since the index is different.
