### ISSUE TITLE
Housing Map Views

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-regional-viz#4]

**Comment by daragoldberg** [comment]
Housing variable, [Map Title] Subcategory by Corresponding Geography, and associated year or change period (type of visualization)

-**HouO16**, **HouR16**, **HouV16** Housing Units by Tenure [Owner Occupied, Renter Occupied, Vacant], 2012-2016 5YR Average (Integrated Dot Density OR Separate Variable Views- mapped at Census Tract)
*Note, these variables are components of Hou16 (Total units) and add to 100%*

-**Houp1016** Total Housing Units Permitted by County, 2010 to 2016 (Chloropleth)

-**HoupS1016**, **HoupM1016** Housing Units Permitted by Municipality, Units in 1-2 Unit Building (S) vs. 3+ Unit Building (M), 2010 to 2016 (Integrated Dot Density OR Separate Variable Views - mapped at municipality _See Long Island Exception_

**Comment by chriswhong** [comment]
Covered by #33
