### ISSUE TITLE
t branch

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-regional-viz#47]

**Comment by allthesignals** [comment]
This seems like a typo?

**Comment by andycochran** [comment]
🤗

**Comment by allthesignals** [comment]
............................................................

**Comment by allthesignals** [comment]
![image](https://user-images.githubusercontent.com/5004319/36800229-014ced8c-1c7d-11e8-8132-25b2f4fa7437.png)

**Comment by andycochran** [comment]
<img src="http://www.bterrier.com/wp-content/uploads/2017/03/what-about-the-blue-or-grey-boston-terrier-dogs.jpg">
