### ISSUE TITLE
Previous/Next buttons need updated

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-regional-viz#57]
Right now, they navigate through everything, but they should navigate through filtered narratives

**Comment by andycochran** [comment]
On `develop` the prev/next narrative links only cycle through 6 maps (7 including the introduction). There are 8 maps in the dropdown menus (which filter out the intro). This seems right to me.

**Comment by allthesignals** [comment]
Cool - I think I had missed some commits
