### ISSUE TITLE
User will see all data visualized at municipality, county, and subregion geographies

### ISSUE THREAD

**Issue by daragoldberg** [NYCPlanning/labs-regional-viz#6]
User can view all data variables within categories (People, Housing, Jobs) at municipality, county, and subregion geographies.

**Comment by andycochran** [comment]
I'm gonna stub in a geography level switcher UI (similar to what's on PFF)…

**Comment by daragoldberg** [comment]
@andycochran great. Just noting that census tract should not be available to user

**Comment by andycochran** [comment]
New branch: `6-geog-switcher`

@allthesignals, @chriswhong, Y'all can use this branch when you're ready to get geog level switching working. 

![image](https://user-images.githubusercontent.com/409279/36607184-e2ab3e7a-1893-11e8-9213-2ea910ce9c10.png)

**Comment by chriswhong** [comment]
Config should indicate which geography levels are available for a given narrative.

Switching geography levels is effectively hiding/showing maps.

Need to figure out how to add "non-primary" layers to maps, where are they defined, etc?

Not all narratives will not have the same options for geometry-level switching, the UI should be config-driven, need to add geometry level property to config.

Config should also indicate which geometry level is default for a narrative.

**Comment by allthesignals** [comment]
Okay so the workflow will be:

 - Add separate entries to `map.layers` for each summary level
 - Add new entries to a third property on `map`, maybe called `toggles`, which maps some summary level information, presentation/display text, etc, to a named layer id.
