### ISSUE TITLE
When toggling a summary level mode and navigating, maps appear blank

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-regional-viz#65]
1. Toggle municipality for a layer
2. Navigate to a layer without municipality

Map will be blank

There should be better handling for this

**Comment by andycochran** [comment]
This shouldn't be an issue. When navigating to a map, the `geographyLevel` should be reset to that map's default level. I don't think that's documented in an issue, so we can change this one to be about that.

**Comment by allthesignals** [comment]
I don't follow... I'm saying it should be toggled to default.

**Comment by andycochran** [comment]
The selected `geographyLevel` should not persist across maps. It should alway reset to the maps' default, regardless of whether the `geographyLevel` on the previous route is available on the route being navigated to.

**Comment by allthesignals** [comment]
Aaah gotcha. Hmm. I think we're passing the geographyLevel down from the controller. Since controllers are singletons, the state will persist. Or, maybe we adjust the scope param? Not sure.

**Comment by andycochran** [comment]
I think we should add `defaultGeographyLevel: [subregion, county, municipality]` to each `map.yaml` and use that to set it on the controller. I'll try to take this one…

**Comment by andycochran** [comment]
The `map.js` controller never needs to know about the geography level. I've successfully moved that to a computed in `map-from-id.js`. Just need to finish that up (finding it to be buggy after switching levels).
