### ISSUE TITLE
Add logic for excluding geometries to choropleth configs

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-regional-viz#69]
There is logic for excluding geometries that are not significant from visualizations.

This issue is complete when all rules are followed:

Jobs:
- [ ] Total Population - Municipality
- [ ] Population Density - Municipality
- [ ] Foreign Born - All
- [ ] Prime Labor Force Change, Subregion and County

Housing
- [ ] Total Housing Units - All
- [ ] Housing Units Permitted - Municipality

**Comment by daragoldberg** [comment]
reconsidered: map all geometries for user and use pop up to indicate data reliability.
