### ISSUE TITLE
User will see certain variables visualized at census tract geography, but clickable selection limited to closest corresponding municipality

### ISSUE THREAD

**Issue by daragoldberg** [NYCPlanning/labs-regional-viz#7]
The following **variables** would be visualized at the census tract geography, but census tract geography would not be selectable/has no corresponding profile. User click would correspond to the closest municipal geography (either boundary or within boundary):

Done:

**Hou16** Total Housing Units, 2012-2016 5YR Average
- **HouO16**  Owner-occupied Housing Units, 2012-2016 5YR Average
- **HouR16**  Owner-occupied Housing Units, 2012-2016 5YR Average
- **HouV16**  Owner-occupied Housing Units, 2012-2016 5YR Average

Still needs to be made:

**EmTot15** Total Employment 2015
**EmPr15** Total Private Employment 2015
- **EmOff15** Private Office-Based Employment 2015
- **EmIns15** Private Institutional Employment 2015
- **EmInd15** Private Industrial Employment 2015
- **EmSer15** Private Retail, Leisure and Hospitality Employment 2015
- **EmOth15** Private Other Services Employment 2015

**Comment by andycochran** [comment]
#8 is closed, can this be?
