### ISSUE TITLE
User can download data on the about page

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-regional-viz#73]
Add links to each of the main tables used by the app on the About page.

**Comment by chriswhong** [comment]
https://planninglabs.carto.com/api/v2/sql?q=SELECT * FROM region_region_v0&format=SHP

https://planninglabs.carto.com/api/v2/sql?q=SELECT * FROM region_subregion_v0&format=SHP

https://planninglabs.carto.com/api/v2/sql?q=SELECT * FROM region_county_v0&format=SHP

https://planninglabs.carto.com/api/v2/sql?q=SELECT * FROM region_municipality_v0&format=SHP

https://planninglabs.carto.com/api/v2/sql?q=SELECT * FROM region_censustract_v0&format=SHP

**Comment by andycochran** [comment]
@chriswhong Do you have any thoughts on the text for these download buttons? Should tell the user what data each link gives them.

**Comment by chriswhong** [comment]
I think at the least we should offer SHP and CSV options for all 5...  
dataset name <SHP> <CSV>
