### ISSUE TITLE
Percent Legends are showing all Zeroes

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-regional-viz#76]

**Comment by chriswhong** [comment]
![labsregionalviz](https://user-images.githubusercontent.com/1833820/36921507-a0729608-1e32-11e8-80d3-584aa2327a4e.png)

**Comment by daragoldberg** [comment]
Same for Foreign Born %
![InnerNJ_subreg.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a8c76cff9bb7f00138499c4/125516c66e82c728ace21e0d46c19a942690ad83b0faaa41b658f7d665043761260ea62864c7b96aea4323025b0c4aae455b5e40fdff892ba4b13a25df0d0fbec3714d36976345f3e5db55ea43a82a994e83bcbd8f4ec0ea3a25e48c8b4f391b1755.jpg)

**Comment by chriswhong** [comment]
New rules for percentage legends:
- For change (population change) prepend plus and minus signs.
- For percent of total (foreign born) do not prepend (+),  show one decimal place of precision.
