### ISSUE TITLE
Load spinners

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-regional-viz#77]
#### User Story
I want to see load spinners so I know something is happening after clicking

#### Description
We need load spinners to communicate that something is happening.

We need to decide whether to use tasks or promises or just use the normal loading substates

**Comment by andycochran** [comment]
New branch `feature/77-map-loading-spinner` has a placeholder spinner:  

```
{{#if loading}}
  {{fa-icon 'spinner' class="fa-spin dark-gray fa-5x map-loading-spinner"}}
{{/if}}
```

Currently, `loading: true` is  hardcoded. We need to listen for when MapboxGL is done rendering. There's a [MapDataEvent](https://www.mapbox.com/mapbox-gl-js/api/#mapdataevent) we can use as we did in ZoLa: [JS](https://github.com/NYCPlanning/labs-zola/blob/develop/app/components/main-map.js#L298-L312), [HBS](https://github.com/NYCPlanning/labs-zola/blob/a0dc7bee80a431b9005f036cfcff12d42a994906/app/templates/components/main-map.hbs#L135).  But I'm not sure exactly how to port this over.

**Comment by andycochran** [comment]
<img width="735" alt="screen shot 2018-03-29 at 2 38 22 pm" src="https://user-images.githubusercontent.com/409279/38107073-e59975da-335e-11e8-8f6a-b0365e83408c.png">

**Comment by andycochran** [comment]
Looks like it was a conscious choice. 

![image](https://user-images.githubusercontent.com/409279/40684743-2faea81c-6360-11e8-88be-117e5a8febf0.png)

I wonder if a refactor along the way broke it. I'll look at the commit history, stand by…
