### ISSUE TITLE
Landing page map content

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-regional-viz#78]
Customer would like the intro page to show the 3 geographies outlined.

**Comment by chriswhong** [comment]
Update: Show municipality outlines and rail lines on the landing page

**Comment by andycochran** [comment]
There'll be no popup content or legend, right? We're just basically showing what the metro area is?

**Comment by daragoldberg** [comment]
geography labels?

**Comment by andycochran** [comment]
The intro map's geographies don't need to be clickable just to read the geog name. So, #74 will solve showing the labels. 

But this means we'll need to add something like `hide-popups` to the map config, set it with a computed property in the `map-from-id` component,  and wrap the `{{map.on 'click'...`action in an `unless`. 

Also, the labels that show on hover shouldn't use the same popup element as the detailed click popups, or that UI will get weird.

**Comment by chriswhong** [comment]
I think labels are useful on this map for anything above municipality level... I'll mess with it a bit and see how they look.
