### ISSUE TITLE
User can view municipality-geo dot density change gains and losses. Municipalities with no statistical significance not visualized.

### ISSUE THREAD

**Issue by daragoldberg** [NYCPlanning/labs-regional-viz#8]
For all municipalities with dot density change visualizations, where variable representing statistical significance of change is greater than 1.645 ("variable"Sig>1.645): 

-visualize data on the map with consistent size threshold
- represent gains in color 1
- represent losses in color 2

If "variable"Sig <1.645
-do not visualize municipality data on the map

**Comment by allthesignals** [comment]
@daragoldberg I think we're just waiting on getting the dot density analysis as point feature in a shapefile. Then we can add them.

**Comment by allthesignals** [comment]
The alternative to that in case you are having trouble will be for me to re-create that analysis in QGIS. The risk there is that I'm afraid of missing some nuance of your analysis
