### ISSUE TITLE
Fix LI municipality geo display for housing units permitted

### ISSUE THREAD

**Issue by daragoldberg** [NYCPlanning/labs-regional-viz#83]
If possible, resolve or make clearer boundaries where town data is represented vs. incorporated villages (i.e. places reporting data). Add logic for muni display?

**Comment by chriswhong** [comment]
Discussed in sprint planning: Modify SQL queries to 
-  [ ]  exclude LI municipalities with zero values on housing permit maps.
-  [ ]  exclude LI towns on all other municipality views

**Comment by daragoldberg** [comment]
For "exclude LI Municipalities with no data _(i.e. HoupTest=N, different than 0 value)_ on housing permit maps, exclude the following geoids:

3601011, 3604143, 3604154, 3604550, 3604891, 3605661, 3605738, 3606387, 3612419, 3621578, 3622480, 3622502, 3622623, 3624273, 3627309, 3628189, 3628200, 3629245, 3629421, 3630202, 3630598, 3632094, 3632105, 3634198, 3634286, 3634374, 3637583, 3638539, 3641003, 3642081, 3642279, 3643192, 3644792, 3644897, 3644908, 3645986, 3646668, 3650067, 3651517, 3653231, 3653253, 3653264, 3653275, 3653748, 3653792, 3654441, 3654551, 3655992, 3658409, 3658442, 3658849, 3659520, 3663506, 3663814, 3664441, 3664842, 3666058, 3666102, 3669001, 3669188, 3669892, 3672554, 3676089, 3676287, 3678146, 3680225, 3682744, 3682942, 3601594, 3602374, 3604055, 3604913, 3604935, 3605039, 3607069, 3607157, 3608026, 3608136, 3609000, 3611781, 3613376, 3613420, 3613442, 3613552, 3616958, 3617530, 3618146, 3618157, 3619466, 3619972, 3620687, 3621985, 3622200, 3622315, 3622447, 3622546, 3622612, 3622733, 3622810, 3622832, 3622980, 3623316, 3624405, 3625417, 3625839, 3625923, 3626121, 3626946, 3628990, 3629509, 3630235, 3630543, 3630581, 3631445, 3631896, 3632732, 3635056, 3635254, 3636233, 3637044, 3637869, 3638022, 3638253, 3639672, 3640838, 3641465, 3645139, 3646074, 3646140, 3646404, 3646514, 3646976, 3647306, 3648054, 3648450, 3649066, 3649424, 3649825, 3650727, 3651396, 3651418, 3651440, 3651495, 3651528, 3652078, 3653198, 3653319, 3653561, 3653775, 3653852, 3654056, 3654112, 3654144, 3655321, 3656968, 3659377, 3660408, 3661142, 3661665, 3661973, 3662066, 3663319, 3663473, 3664584, 3665409, 3666212, 3666481, 3666828, 3666850, 3667048, 3667070, 3667851, 3668374, 3669254, 3669452, 3670387, 3671608, 3671620, 3673352, 3675572, 3677772, 3677805, 3678575, 3679246, 3679301, 3680170, 3680258, 3680302, 3680885, 3681419, 3683294, 3683426

**Comment by daragoldberg** [comment]
For "exclude LI towns on all other municipality views", **exclude the following geoids**

3605934000, 3605953000, 3605956000, 3610304000, 3610310000, 3610322194, 3610337000, 3610338000, 3610361984, 3610366839, 3610368000, 3610368473, 3610369463
