### ISSUE TITLE
Add space to data profile pop up to indicate reliability

### ISSUE THREAD

**Issue by daragoldberg** [NYCPlanning/labs-regional-viz#85]
Add space for small text in bottom of profile pop up for standard text describing data reliability

**Comment by andycochran** [comment]
This should be a small message which displays if some data is grayed out? 

> Grayed values are not statistically reliable.

^ Something like this?

**Comment by daragoldberg** [comment]
Yes, also add another column to indicate MOE

**Geography** |   Estimate | . "+/-MOE"
