### ISSUE TITLE
Add boundaries for all geos (subregion, county, municipality) for dot density maps with data mapped to/locked to tract

### ISSUE THREAD

**Issue by daragoldberg** [NYCPlanning/labs-regional-viz#89]
All geo boundaries (Subregion, County, Municipality) should be displayed on top of tenure dot density mapped to tract. Can toggle between and select geos.

**Comment by chriswhong** [comment]
Switching geos is ONLY for showing boundaries as a reference, the dot density visualization will remain, switching geos will also cause the popup to change its context.

**Comment by chriswhong** [comment]
https://regional-viz.planninglabs.nyc/People/prime-labor-force-gain#10.06/40.694/-73.8452

Prime labor force is a special case where County and above show a choropleth, only municipality shows dot density.  Need to figure out how accomodate this in the configs
