### ISSUE TITLE
Legend labels for change maps formatted to indicate +/- value

### ISSUE THREAD

**Issue by daragoldberg** [NYCPlanning/labs-regional-viz#92]
For maps indicating change, all values in legend should indicate gain or loss by "+#,###" or "-#,###".  Top/bottom breaks should read "Loss of #,### or more" / "Gain of more than #,###"

**Comment by daragoldberg** [comment]
i.e.  "Gain of more than 50,000
"+15,001 - +50,000
+1,501 - +15,000
-5,000 - +1,500
Loss of 5,000 or more
![ChangeLegendTitle.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a8c76cff9bb7f00138499c4/125516c66e82c728ace21e0d46cb9c9b2d8586858aeeba4da069f9802543653f6b14b1247a80e03cfd1839540e571da8125c5d40fff88d2aa0b63c728d5a5eb880690c66da2f53fde6d640e258f075c95d8fa4bd8346c1ed3f25e58c8f493a1806118ced10.jpg)

**Comment by chriswhong** [comment]
We need a flag in the config that says whether it is a change measurement...  `isChangeMeasurement` perhaps.

**Comment by daragoldberg** [comment]
Change maps:
**PEOPLE** (all geos)
-Net population change
-% population change
-labor force change 

**JOBS** (subregion & county only)
-private employment change
-private employment change by sector(?) _[not in the map yet, would be nice to add]_
- office
- institutional
- industrial
- local services
- other services
