### ISSUE TITLE
Fix municipality select option for prime labor force change

### ISSUE THREAD

**Issue by daragoldberg** [NYCPlanning/labs-regional-viz#94]
When municipality toggled on, pop up and select is tied to county geo and not muni geo.

**Comment by daragoldberg** [comment]
Pop up/select options tied to county: 
![PWork-MuniCounty_geo.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a8c76cff9bb7f00138499c4/125516c66e82c728ace21e0d46d8a3953189ce849ae7b660ab48fe80307920762646ef696097ec22ba416f43554d4bfd490b5b17f8fb8d28a7b23d768a5c09ead7380a25c26e03b0aac04ee155e57dd205d0f4ae805ec2e93724e2898f4d391f0d1988f8593cb2d4.jpg)

**Comment by andycochran** [comment]
Fixed.
