### ISSUE TITLE
Add "Balance" as 4th drop-down category to menu

### ISSUE THREAD

**Issue by daragoldberg** [NYCPlanning/labs-regional-viz#96]
4th narrative category, should now be People, Housing, Jobs, **Balance**

**Comment by chriswhong** [comment]
Only visualize County and Subregion.  (All Choropleths)

- [ ] Housing/Jobs 2000
- [ ] Housing/Jobs -2016
- [ ] Housing Change

**Comment by daragoldberg** [comment]
**Housing/Jobs 2000  - Subregion**
_Breaks_
0.825
0.85
0.9
0.95

_colors_
#127723
#89dfa4
#ffffe0
#ffa555
#d76523

**Comment by daragoldberg** [comment]
Housing/Jobs 2000 - County
Breaks
0.4
0.6
0.85
0.9
1.15
1.75

colors
#193f1f
#127723
#89dfa4
#ffffe0
#ffa555
#d76523
#87390c

**Comment by daragoldberg** [comment]
**Housing vs. Job Change 2000-2016 Subregion**
variable: BalHpJ0016

_breaks_
-50000
-15000
+15000
+50000

_colors_
#127723
#89dfa4
#ffffe0
#ffa555
#d76523

**Comment by daragoldberg** [comment]
**Housing vs. Job Change 2000-2016 County**
variable: BalHpJ0016

_breaks_
-50000
-15000
-5000
+5000
+15000

_colors_
#d76523
#ffa555
#ffffe0
#89dfa4
#127723
#193f1f

**Comment by daragoldberg** [comment]
same as #116
