### ISSUE TITLE
Re-order "Housing" drop-down maps & rename

### ISSUE THREAD

**Issue by daragoldberg** [NYCPlanning/labs-regional-viz#98]
1- Total Housing Units
2- Housing Units, Owner- vs. Renter-Occupied
3- Housing Units by Building Size [NEED TO ADD - see Google Sheet]
4- Total Housing Units Permitted
5- Housing Units Permitted by Building Size

**Comment by chriswhong** [comment]
#3 Above is a dot density similar to #2
